services:
  client:
    restart: always
    image: yakirbartech/agentic-client:0.1  
    container_name: client
    ports:
      - "5175:5175"
    depends_on:
      - backend

  backend:
    restart: always
    image: yakirbartech/agentic-backend:0.1  
    container_name: backend
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
      PG_PORT: 5432

  postgres:
    restart: always
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_pass
      POSTGRES_DB: sso_db

  pgadmin:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  n8n:
    restart: always
    image: docker.n8n.io/n8nio/n8n
    command: start --tunnel
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data:
  pgadmin_data:
  postgres_data:
